In [1]:
import numpy as np

# Uniform Distribution

In [6]:
u = np.random.uniform(0,1,3)
display(u)
u = np.random.uniform(-5,5,3)
display(u)

array([0.10788669, 0.78170181, 0.34600885])

array([ 3.63535072,  1.03392308, -0.25518341])

# Normal (Gaussian) dist. : np.random.normal()

Number CLuster around the mean with spread determined by stan. deviation
Bell Shaped Curve
Standard Deviation

In [ ]:
display(np.random.normal(0,1,3))

display(np.random.normal())

array([ 1.81619656, -0.32586956, -0.82810868])

# np.randome.rand()