In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# NumPy Questions


1 Create a 5×5 matrix with values 1 to 25, then rotate it 90 degrees clockwise without using loops.

In [4]:
arr = np.arange(1, 26).reshape(5, 5)
rotated = np.rot90(arr, -1)   # -1 → clockwise rotation

print("Original:\n", arr)
print("\nRotated 90° clockwise:\n", rotated)

Original:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Rotated 90° clockwise:
 [[21 16 11  6  1]
 [22 17 12  7  2]
 [23 18 13  8  3]
 [24 19 14  9  4]
 [25 20 15 10  5]]


2 Generate a 10×10 matrix of random integers (1–100), and replace all even numbers with 0 using boolean indexing.

In [5]:
arr = np.random.randint(1, 101, size=(10, 10))
arr[arr % 2 == 0] = 0

print(arr)


[[67  0  0 73  0 25 85 47  0  0]
 [57  0 81  0  0  0 29 91  0  0]
 [ 0  0 13  0  0 19 53  0  0 49]
 [ 7  0 25  0  0 47 97  0  0  0]
 [ 0  1 75 81  0 11  0  0  1 17]
 [57 73  0  0 31 37  0 99 15  0]
 [ 0 57 55  0  0  0 43 85 71  0]
 [37  0  0 89  0 31  9 77 93  0]
 [ 0 25  0 61  0 25 21  0 97 31]
 [ 0  0  0 81 61  0 71 17  0 51]]


3 Create a 3×3 matrix and compute its eigenvalues and eigenvectors.

In [6]:
A = np.array([[4, -2, 1],
            [1, 1, -1],
            [3, -2, 4]])

eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:\n", eigenvalues)
print("Eigenvectors:\n", eigenvectors)


Eigenvalues:
 [5.95137304+0.j         1.52431348+0.73003568j 1.52431348-0.73003568j]
Eigenvectors:
 [[-0.51075995+0.j         -0.49953142-0.26551578j -0.49953142+0.26551578j]
 [ 0.0699032 +0.j         -0.76458436+0.j         -0.76458436-0.j        ]
 [-0.85687678+0.j         -0.09864953+0.29265808j -0.09864953-0.29265808j]]


4 Simulate 1000 coin flips using NumPy, and calculate the probability of getting exactly 500 heads.

In [7]:
flips = np.random.randint(0, 2, size=1000)  # 0 = Tails, 1 = Heads
heads = np.sum(flips)

prob = np.isclose(heads, 500).astype(int)  # check if exactly 500 heads

print(f"Number of heads: {heads}")
print("Probability of exactly 500 heads ≈", prob/1)  # 1 trial


Number of heads: 470
Probability of exactly 500 heads ≈ 0.0


5 Create a 6×6 identity matrix, then replace its diagonal with numbers from 1 to 6.

In [8]:
arr = np.eye(6, dtype=int)
np.fill_diagonal(arr, np.arange(1, 7))

print(arr)


[[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]


6 Create two 3×3 matrices and compute their matrix multiplication manually (without np.dot or @), using broadcasting.

In [9]:
A = np.array([[1, 2, 3],
            [4, 5, 6],
            [7, 8, 9]])

B = np.array([[9, 8, 7],
            [6, 5, 4],
            [3, 2, 1]])

# Manual matrix multiplication: sum(A[i,k] * B[k,j])
C = (A[:, :, None] * B.T[None, :, :]).sum(axis=1)

print(C)


[[ 46  28  10]
 [118  73  28]
 [190 118  46]]


7 Generate 1 million random numbers from a normal distribution (mean=50, std=10). Compute mean, variance, and standard deviation using NumPy functions.

In [10]:
data = np.random.normal(50, 10, 1_000_000)

print("Mean:", np.mean(data))
print("Variance:", np.var(data))
print("Standard Deviation:", np.std(data))


Mean: 50.0034514022623
Variance: 99.92428116841262
Standard Deviation: 9.996213341481495


8 Create a 1D array of length 100 with values from 1 to 100. Then, reshape it into a 3D array of shape (5, 5, 4). Verify the reshape worked by checking its sum.

In [11]:
arr = np.arange(1, 101)

reshaped = arr.reshape(5, 5, 4)

print("Original sum:", arr.sum())
print("Reshaped sum:", reshaped.sum())


Original sum: 5050
Reshaped sum: 5050


9 Create a 7×7 checkerboard pattern (alternating 0s and 1s) using NumPy slicing, without loops.

In [12]:
# Initialize 7x7 zeros
checkerboard = np.zeros((7, 7), dtype=int)

# Fill alternate squares with 1
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1

print(checkerboard)


[[0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0]]


10 Generate a 4×4 random integer matrix (1–20). Replace every element that is the maximum in its row with -1.

In [13]:
# Generate random 4x4 integer matrix
arr = np.random.randint(1, 21, size=(4, 4))
print("Original Matrix:\n", arr)

# Find row-wise maximums
row_max = arr.max(axis=1, keepdims=True)

# Replace max elements with -1
arr[arr == row_max] = -1

print("\nModified Matrix (row max → -1):\n", arr)


Original Matrix:
 [[ 1 14 17 17]
 [10  6 17 18]
 [ 4 20  3 20]
 [14 12 19  7]]

Modified Matrix (row max → -1):
 [[ 1 14 -1 -1]
 [10  6 17 -1]
 [ 4 -1  3 -1]
 [14 12 -1  7]]
