In [2]:
import numpy as np

In [7]:
#Simple Array
arr1 = np.array([1,2,3,4,5])
print("1D Array:", arr1)
x=np.sum(arr1)
y=np.mean(arr1)
print("Sum: ",x)
print("Mean: ",y)

1D Array: [1 2 3 4 5]
Sum:  15
Mean:  3.0


In [6]:
#2d array
arr2 = np.array([[1,2,3],[4,5,6]])
print("2D Array: \n",arr2)

2D Array: 
 [[1 2 3]
 [4 5 6]]


In [9]:
arr1=[1,2,3,4,5]
arr2=[6,7,8,9,10]
x=np.sum(arr1,arr2)
y=np.mean(arr1,arr2)
z=np.average(arr1,arr2)
print(f"Sum: {x}")
print(f"Mean: {y}")
print(f"Average: {z}")


TypeError: 'list' object cannot be interpreted as an integer

In [14]:
random_arr = np.random.rand(2,2)
print("Random Array: ")
print(random_arr)

Random Array: 
[[0.50359644 0.51058279]
 [0.76506364 0.37461825]]


In [ ]:
print(np.shape(random_arr))
np.size(random_arr)


(2, 2)


4

: 